name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install
          poetry run django-admin startproject core
          mv al_uloum core

          # Settings
          echo "INSTALLED_APPS = [" >> core/settings.py
          echo "'al_uloum'," >> core/settings.py
          echo "'al_uloum.apps.home'," >> core/settings.py
          echo "'al_uloum.apps.indexes'," >> core/settings.py
          echo "'al_uloum.apps.pages'," >> core/settings.py
          echo "'al_uloum.apps.sections'," >> core/settings.py
          echo "'al_uloum.cms'," >> core/settings.py
          echo "'wagtail.contrib.forms'," >> core/settings.py
          echo "'wagtail.contrib.redirects'," >> core/settings.py
          echo "'wagtail.embeds'," >> core/settings.py
          echo "'wagtail.sites'," >> core/settings.py
          echo "'wagtail.users'," >> core/settings.py
          echo "'wagtail.snippets'," >> core/settings.py
          echo "'wagtail.documents'," >> core/settings.py
          echo "'wagtail.images'," >> core/settings.py
          echo "'wagtail.search'," >> core/settings.py
          echo "'wagtail.admin'," >> core/settings.py
          echo "'wagtail'," >> core/settings.py
          echo "'modelcluster'," >> core/settings.py
          echo "'taggit'," >> core/settings.py
          echo "]" >> core/settings.py

      - name: Run checks and tests
        run: |
          source .venv/bin/activate
          poetry run python core/manage.py migrate
          poetry run python core/manage.py check
          poetry run python core/manage.py test
